### ISSUE TITLE
Attribute with builtin name

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/python-openflow#301]
In `/v0x04/common/queue.py`, `class QueuePropHeader` has an attribute called `property`, which is a Python builtin name. Is this needed somehow?

**Comment by abaruchi** [comment]
@renanrodrigo I guess it is necessary. According to the spec 1.3 and 1.3.5, the structure has a field called `property`. So, I believe we should leave it as it is now.
@beraldoleal Should we close this issue?

Thanks

```
/* Common description for a queue. */ 
struct ofp_queue_prop_header {
	uint16_t property; /* One of OFPQT_. */
	uint16_t len; 	   /* Length of property, including this header. */
	uint8_t pad[4];    /* 64-bit alignment. */
};
OFP_ASSERT(sizeof(struct ofp_queue_prop_header) == 8);
```

**Comment by beraldoleal** [comment]
@abaruchi not yet. From PEP8:

"If your public attribute name collides with a reserved keyword, append a single trailing underscore to your attribute name. This is preferable to an abbreviation or corrupted spelling."

As discussed before, we must try as hard as possible to comply with the specification in order to make easy for new devs to understand our library.

At same time we should not broke PEP8. So I'm in doubt... `queue_property`  vs `property_`.

**Comment by beraldoleal** [comment]
I think that we can go for now with `queue_property` as discussed here #217
