### ISSUE TITLE
Ensure that get_size method delegates to each attribute get_size method

### ISSUE THREAD

**Issue by beraldoleal** [kytos/python-openflow#61]
Now, get_size method needs a refact following unpack logic. Each class that has get_size should implement respective get_size if necessary.

**Comment by cemsbr** [comment]
We can get the struct size by using `get_size()` in each class attribute. However, some structs have a variable-length field and the user can provide bytes directly instead of a BinaryData instance. I was thinking about overriding `get_size()` in these cases, only. Other ideas?

**Comment by cemsbr** [comment]
Instead of overriding, I'm considering to have only one implementation that checks if the last class attribute is named "data".

**Comment by diraol** [comment]
I think that we need to decide what the "get_size" method is going to return.

The "real"/"actual" size of the openflow message instance (object) or the "expected size" of the message.

On the first case, we should consider the values that the user added to the object, even if he had added values that does not fit on the attribute (it will raise an error during packing).

On the second case we are calculating the class size, which is the size that the packet will have after being packed.

I think that the first case should be the correct one, and it have a strong relationship with the length on the header (on the case of GenericMessages, not GenericStructs).

For me, the get_size method should return the "current size" of the object (and eventually raise exceptions in the case that the data does not fit the field).

Regarding your second message, about not overriding and using an if statement on the 'general' method, I tend to disagree with this approach. Mainly because we are not "delegating" the responsibility to the attribute, that is the behavior that we are looking for.

**Comment by cemsbr** [comment]
I agree that we should calculate the real size and raise an error if a value doesn't fit the struct (by using the `validate` method of the next milestone).

I'm delegating the behavior and it will be easier to show you the code instead of explaining it here.

**Comment by diraol** [comment]
Nice! Agreements! =)

About the "if" and the "delegation", may be we can use the same approach we used on the "pack" method, calling the class attribute get_size method and passing the instance attribute "content" as argument to it. Then, any specific logic will be handled by the get_size method from the attribute (being it a UBIntX, GenericStruct, BinaryData or any List).
