### ISSUE TITLE
parsing/unpacking multi-part responses

### ISSUE THREAD

**Issue by brownbytes** [kytos/python-openflow#614]
Hi

I am using python-openflow library as standalone library for an Asyncio based SDN controller.
are there any examples that I can refer to to understand unpacking of multipart messages such as flow-stats message??

**Comment by renanrodrigo** [comment]
Hello,

It should be workling out of the box, using the unpack method from pyof.utils.

Could you please post a snippet of how you are doing the unpack?
I checked the exception in your initial text, but seeing how you got to that would make it easier to give you directions.

**Comment by brownbytes** [comment]
Hi,

Thank you for the response. I am infact using 'unpack' method from utils. this is a snippet

```
        while True:
            b_pkt = await self.loop.sock_recv(clientsock, 1024)
            try:
                pkt = unpack_message(b_pkt)
            except:
               # pkt = MultipartReply.unpack(b_pkt)
                print("error::",sys.exc_info())
                raise
```

**Comment by renanrodrigo** [comment]
You are importing unpack_message from v0x04, right?

I can suggest you some things:

1. Usually I'm not using the unpack_message directly - you could use the wrapper.
Instead of `from pyof.v0x04.common.utils import unpack_message` you can use `from pyof.utils import unpack`. The wrapper is going to do some checks - and maybe raise more meaningful exceptions - as well as select the proper version to unpack the binary data.

2. Check the binary data you are receiving. The package should start with `0x04 0x13` (as a multipart reply), but in your dump it starts with `0xFF 0xFF` Even if you have just the headerless message, this kinda doesn't make sense for me.

Forward into that, I have some doubts about your exception dump being a flow-stats message. Looking at the binary data, I would say this is a Port Description packet, although incomplete or malformed.

I would say this is a problem in the way your controller is handling the messages.

**Comment by brownbytes** [comment]
I have indeed used unpack_message from common.utils. So, I check my program to use unpack wrapper. Thank you for this suggestion.
I had encountered exceptions with both port stats and flow stats messages.
Thank you again.

**Comment by renanrodrigo** [comment]
@brownbytes No problem. If your debugging process finds something else, feel free to reach out or reopen the issue.

@hdiogenes, I think this can be closed for now.

**Comment by hdiogenes** [comment]
Closing now. Thank you a lot, @renanrodrigo!
